# Generated by Django 5.2.3 on 2025-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Title')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='URL Title')),
                ('is_active', models.BooleanField(verbose_name='Active / Inactive')),
                ('is_delete', models.BooleanField(verbose_name='Deleted / Not Deleted')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Product Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='Product Image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='Short Description')),
                ('description', models.TextField(db_index=True, verbose_name='Main Description')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('is_delete', models.BooleanField(verbose_name='Deleted / Not Deleted')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
