# Generated by Django 5.2.3 on 2025-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('massage', models.TextField(null=True, verbose_name='massage')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response')),
                ('is_ready_by_admin', models.BooleanField(default=False, verbose_name='read by admin')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'list Contact Us',
            },
        ),
    ]
