# Generated by Django 5.2.3 on 2025-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title company')),
                ('description', models.TextField(db_index=True, verbose_name='description')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email company')),
                ('phone', models.CharField(max_length=50, verbose_name='phone company')),
                ('fax', models.CharField(max_length=50, verbose_name='fax company')),
                ('address', models.CharField(max_length=360, verbose_name='address')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/poster', verbose_name='poster')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About US',
            },
        ),
    ]
